[package]
name = "starknet_multicall"
version = "0.1.0"
cairo-version = "2.8.4"
scarb-version = "2.8.4"
authors = ["Huynh Duc Duy <@huynhducduy>"]
license = "MIT"
keywords = ["starknet", "smart-contract", "cairo"]
description = "True multicall on starknet"
documentation = "https://dew-labs.github.io/starknet_multicall/"
homepage = "https://dew-labs.github.io/starknet_multicall/"
repository = "https://github.com/dew-labs/starknet_multicall"
readme = "README.md"
experimental-features = ["negative_impls"]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.8.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.32.0" }

[tool.snforge]
exit_first = false

[tool.fmt]
sort-module-level-items = false
tab-size = 4 # Obey .editorconfig
max-line-length = 120
